### ISSUE TITLE
Gradle build output hidden when running application

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#19] opened 2018-03-16 13:52 UTC
_From @cavatron on March 16, 2018 3:34_

After following the [quickstart](https://nativescript-vue.org/en/docs/getting-started/quick-start/), I tried to add a jar file to the gradle build, however, the build fails without much explanation.

Here is my `<project-root>/template/app/App_Resources/Android/app.gradle` file (where I assume I should be adding native Android dependencies)
```
// Add your native dependencies here:
android {
  defaultConfig {  
    generatedDensities = []
    applicationId = "__PACKAGE__"
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
} 

dependencies {
  // This is just an example. I am unable to add any library without gradle build failing
  compile 'org.apache.logging.log4j:log4j-api:2.10.0'
}

```
I have tried running `tns run android --log trace` with no luck. It does not show gradle errors.

Here is the output of running `npm run watch:android` (the command I am using when the error occurs)

```
info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tns-vue-test@ No repository field.

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
Copying template files...
Installing tns-android
Installing  tns-android
+ tns-android@3.4.2
added 1 package in 0.956s
Project successfully created.
Preparing project...
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-vue for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + applying user-defined configuration from /home/cavatron/Repositories/tns-vue-test/dist/app/App_Resources/Android/app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /home/cavatron/Repositories/tns-vue-test/dist/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
false
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
```

Is there a way to make the Gradle output more verbose? When building a NativeScript plugin from the [plugin seed](https://github.com/NativeScript/nativescript-plugin-seed), Gradle shows the full output, which is why I am posting the issue here.

_Copied from original issue: nativescript-vue/nativescript-vue#139_

**Comment by rigor789** [comment] 2018-03-16 13:53
Have you tried `npm run clean` after you have changed your gradle file?

**Comment by cinderisles** [comment] 2018-03-16 15:26
@rigor789 yes, the same error occurs. I can verify that `dist/app/App_Resources/Android/app.gradle` and `template/app/App_Resources/Android/app.gradle` are the same and contain my native dependency reference so it is not an issue with the gradle file being copied over.

**Comment by lewebsimple** [comment] 2018-03-17 11:17
Verbose output and stopping on webpack error are features I'd like to add sometime soon...

**Comment by supergrahn** [comment] 2018-04-30 18:31
Any luck on fixing this error?

**Comment by rigor789** [comment] 2018-04-30 22:39
@supergrahn this is a gradle build error which could mean many things. To check the exact error I suggest going into the `dist` folder and running `tns run build --log trace` which should print a very detailed log about the issue.

**Comment by drehimself** [comment] 2018-05-18 04:08
I'm getting the same error. I'm running an Android emulator. Everything works fine with the iOS simulator.

It seems as if there are missing files in the `/Users/<user>/.gradle/` folder.

Here's my partial output after I run `tns run android --log trace` in the `dist` directory:

```
AfterHookName for command shouldPrepare is after-shouldPrepare
Skipping prepare.
Building project...
spawn: ./gradlew "assembleDebug" "--debug" "--stacktrace" "-PcompileSdk=android-27" "-PtargetSdk=27" "-PbuildToolsVersion=27.0.3" "-PsupportVersion=26.0.0-alpha1" "-PgenerateTypings=false"
Exception in thread "main" java.io.FileNotFoundException: /Users/Dre/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
```

**Comment by ephraimlambarte** [comment] 2018-05-24 15:53
I am having an error too, ever since i installed nativescript-firebase-plugin,
i am using nativescript-vue template and this is my 
repo: https://github.com/eyedeceiver03/utang-application.git  
         on the "ephraim" branch.
`tns run android
Searching for devices...
Skipping prepare.
Building project...
Gradle build...
         + applying user-defined configuration from C:\xampp\htdocs\tmp4\utang-application\dist\app\App_Resources\Android\app.gradle
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: C:\xampp\htdocs\tmp4\utang-application\dist\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: C:\xampp\htdocs\tmp4\utang-application\dist\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\775762f13290c5bf0ff992e20e071fb3\res\values\values.xml: AAPT: error: resource android:attr/fontStyle not found.

C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\775762f13290c5bf0ff992e20e071fb3\res\values\values.xml: AAPT: error: resource android:attr/font not found.

C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\775762f13290c5bf0ff992e20e071fb3\res\values\values.xml: AAPT: error: resource android:attr/fontWeight not found.

C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:7:
error: resource android:attr/colorError not found.
C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:359: error: resource android:attr/fontStyle not found.
C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:359: error: resource android:attr/font not found.
C:\xampp\htdocs\tmp4\utang-application\dist\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:359: error: resource android:attr/fontWeight not found.
error: failed linking references.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
        ... 47 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Unable to apply changes on device: 521023ff581cb3cb. Error is: Command gradlew.bat failed with exit code 1.`

**Comment by luishdez87** [comment] 2018-05-30 04:35
same error here

**Comment by elalienx** [comment] 2018-06-03 19:46
Same error here. I created a empty project using the Vue CLI Template and it runs fine on Android. As soon I install the Firebase plugin it won't compile anymore.

**Comment by Globerada** [comment] 2018-06-05 17:33
help please!

```
Unzipping C:\Users\globerada\.gradle\wrapper\dists\gradle-4.4-all\9br9xq1tocpiv8o6njlyu5op1\gradle-4.4-all.zip to C:\Users\globerada\.gradle\wrapper\dists\gradle-4.4-all\9br9xq1tocpiv8o6njlyu5op1
         + setting applicationId
         + applying user-defined configuration from G:\Escritorio\nativescript\native-app\dist\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: G:\Escritorio\nativescript\native-app\dist\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: G:\Escritorio\nativescript\native-app\dist\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Unable to apply changes on device: 1018679f. Error is: Command gradlew.bat failed with exit code 1

```

I am working in a big project and all it was working fine until I follow the instructions to install Native Script Firebase

https://github.com/EddyVerbruggen/nativescript-plugin-firebase

**Comment by rigor789** [comment] 2018-06-05 21:05
@luishdez87  @elalienx @Globerada see https://github.com/nativescript-vue/vue-cli-template/issues/19#issuecomment-385549892 to check the full log where it fails.

**Comment by elalienx** [comment] 2018-06-10 18:52
In my case was the firebase plugin that I did not configure properly. I don't have the error log anymore because the system works now.

**Comment by Globerada** [comment] 2018-06-10 19:11
@elalienx  so, how did you fix it?

**Comment by Globerada** [comment] 2018-06-13 15:49
@rigor789 , any ideas?

I am trying firebase-plugin in a clean project. Just this plugin. Windows 10 and trying to install in a real Android device (not simulator)

```

G:\Escritorio\nativescript\test-firebase\dist>tns run android
Searching for devices...
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from G:\Escritorio\nativescript\test-firebase\dist\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: G:\Escritorio\nativescript\test-firebase\dist\node_modules\nativescript-plugin-firebase\platforms\android\firebase-release.aar
         + adding aar plugin dependency: G:\Escritorio\nativescript\test-firebase\dist\node_modules\nativescript-plugin-firebase-common\platforms\android\nativescript_plugin_firebase_common.aar
         + adding jar plugin dependency: G:\Escritorio\nativescript\test-firebase\dist\node_modules\nativescript-plugin-firebase-common\platforms\android\firebase-client-android-2.5.2.jar
         + adding aar plugin dependency: G:\Escritorio\nativescript\test-firebase\dist\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.

C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/font not found.

C:\Users\globerada\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a1f2d02a605d5a2aaa25afeb26781598\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Unable to apply changes on device: 1018679f. Error is: Command gradlew.bat failed with exit code 1.

G:\Escritorio\nativescript\test-firebase\dist>
```

**Comment by rigor789** [comment] 2018-06-13 16:23
@Globerada you need to check the full log as outlined in https://github.com/nativescript-vue/vue-cli-template/issues/19#issuecomment-385549892 - and then find the error that makes it fail, and then fix the error

**Closed as completed** 2018-09-15 11:38 UTC
Labels: enhancement
